apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd-instance
  namespace: demo-project
  labels:
    app: argocd
spec:
  server:
    route:
      enabled: true
  sso:
    provider: dex
    dex:
       openShiftOAuth: true
  resourceExclusions: |
    - apiGroups:
        - tekton.dev
      clusters:
        - '*'
      kinds:
        - TaskRun
        - PipelineRun
